--- #YAML:1.0
name:               MediaWiki-Bot-Plugin-SE
version:            0.2.1
abstract:           a plugin for MediaWiki::Bot which contains data retrieval tools for the 2009 Steward elections
author:
    - Dan Collins (ST47)
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    MediaWiki::Bot:  1.5.2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
